//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uCommunity.Server.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization; 
    
    [DataContract]
    public partial class Topic
    {
        [DataMember] 
        public long Id { get; set; }
        [DataMember] 
        public string Title { get; set; }
        [DataMember] 
        public string Content { get; set; }
        [DataMember] 
        public System.Guid CreatedBy { get; set; }
        [DataMember] 
        public System.DateTime CreatedTime { get; set; }
        [DataMember] 
        public Nullable<short> Kind { get; set; }
        [DataMember] 
        public bool IsTop { get; set; }
        [DataMember] 
        public Nullable<int> Sequence { get; set; }
        [DataMember] 
        public long ParentTopic { get; set; }
        [DataMember] 
        public Nullable<int> Category { get; set; }
        [DataMember] 
        public Nullable<System.DateTime> LastUpdated { get; set; }
    
        [DataMember] 
        public virtual User User { get; set; }
    }
}
