//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uCommunity.Server.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization; 
    
    [DataContract]
    public partial class User
    {
        public User()
        {
            this.Topics = new HashSet<Topic>();
            this.Followers = new HashSet<User>();
            this.UserGroups = new HashSet<UserGroup>();
        }
    
        [DataMember] 
        public System.Guid Id { get; set; }
        [DataMember] 
        public string FirstName { get; set; }
        [DataMember] 
        public string LastName { get; set; }
        [DataMember] 
        public string Alias { get; set; }
        [DataMember] 
        public string Email { get; set; }
        [DataMember] 
        public string LoginName { get; set; }
        [DataMember] 
        public string Pwd { get; set; }
    
        [DataMember] 
        public virtual ICollection<Topic> Topics { get; set; }
        [DataMember] 
        public virtual ICollection<User> Followers { get; set; }
        [DataMember] 
        public virtual ICollection<UserGroup> UserGroups { get; set; }
    }
}
