//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uCommunity.Server.Data
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization; 
    
    [DataContract]
    public partial class UserGroup
    {
        public UserGroup()
        {
            this.Users = new HashSet<User>();
        }
    
        [DataMember] 
        public System.Guid Id { get; set; }
        [DataMember] 
        public byte[] Name { get; set; }
        [DataMember] 
        public bool IsEnabled { get; set; }
        [DataMember] 
        public string Description { get; set; }
    
        [DataMember] 
        public virtual ICollection<User> Users { get; set; }
    }
}
